#!/bin/bash
set -e

echo "METABASE_DBNAME=$METABASE_DBNAME"
echo "METABASE_USER=$METABASE_USER"
echo "METABASE_PASS=$METABASE_PASS"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    
    CREATE DATABASE "$METABASE_DBNAME";
    CREATE USER "$METABASE_USER" WITH PASSWORD '$METABASE_PASS';
    GRANT ALL PRIVILEGES ON DATABASE "$METABASE_DBNAME" TO "$METABASE_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$METABASE_DBNAME" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO "$METABASE_USER";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$METABASE_USER";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$METABASE_USER";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT ALL ON TABLES TO "$METABASE_USER";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT ALL ON SEQUENCES TO "$METABASE_USER";
EOSQL