services:
  vasedapi:
    image: chgv99/vasedb-api:latest
    container_name: vasedb-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VASEDB_API_LISTEN_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      VASEDB_API_LISTEN_PORT: ${VASEDB_API_LISTEN_PORT}
      VASEDB_API_KEY: ${VASEDB_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      VASEDB_CLIENT_URL: ${VASEDB_CLIENT_URL}
      VASEDB_API_PER_IP_CAP: ${VASEDB_API_PER_IP_CAP}
      VASEDB_API_PER_IP_TIME: ${VASEDB_API_PER_IP_TIME}
      VASEDB_API_PER_IP_TIME_UNIT: ${VASEDB_API_PER_IP_TIME_UNIT}

volumes:
  postgresql_data: