spring:
  cache:
    cache-names:
      - rate-limit-buckets
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 1200000 # 20 minutes
      refresh-token:
        expiration: 86400000 # 1 day

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/.*
      http-status-code: TOO_MANY_REQUESTS
      http-response-body: "{ \"error\": \"Too Many Requests\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: ${VASEDB_API_PER_IP_CAP}
              time: ${VASEDB_API_PER_IP_TIME}
              unit: ${VASEDB_API_PER_IP_TIME_UNIT}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG