CREATE TABLE public.build (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.build ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.build_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.game (
    total_time real,
    build_id bigint,
    id bigint NOT NULL,
    played_at timestamp(6) without time zone
);

ALTER TABLE public.game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.resolution (
    elapsed_time double precision,
    game_id bigint,
    id bigint NOT NULL,
    solved_at timestamp(6) without time zone,
    speed_qualifier character varying(255),
    vase_attributes json
);

ALTER TABLE public.resolution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resolution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.stage (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.stage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.build
    ADD CONSTRAINT build_name_key UNIQUE (name);

ALTER TABLE ONLY public.build
    ADD CONSTRAINT build_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resolution
    ADD CONSTRAINT resolution_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.stage
    ADD CONSTRAINT stage_name_key UNIQUE (name);

ALTER TABLE ONLY public.stage
    ADD CONSTRAINT stage_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resolution
    ADD CONSTRAINT fk2t7vke7g7hfsxlwp2ecpj3vif FOREIGN KEY (game_id) REFERENCES public.game(id);

ALTER TABLE ONLY public.game
    ADD CONSTRAINT fkon5rsrph7x5clppfytepsp50g FOREIGN KEY (build_id) REFERENCES public.build(id);

INSERT INTO public.build (id, name) VALUES (1, 'dbtest 0.0.1');

INSERT INTO public.stage (id, name) VALUES (1, 'Size');
INSERT INTO public.stage (id, name) VALUES (2, 'Handles');
INSERT INTO public.stage (id, name) VALUES (3, 'Symmetry');
INSERT INTO public.stage (id, name) VALUES (4, 'Color');
INSERT INTO public.stage (id, name) VALUES (5, 'Stickers');
INSERT INTO public.stage (id, name) VALUES (6, 'Pitch');
INSERT INTO public.stage (id, name) VALUES (7, 'Blackout');
