name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DB_HOST,DB_USER,DB_PASSWORD
          script: |
            cd /home/ubuntu/vasedb
            export DB_HOST="${{ secrets.DB_HOST }}"
            export DB_USER="${{ secrets.POSTGRES_USER }}"
            export DB_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"

            export VASEDB_API_LISTEN_PORT= "${{ secrets.VASEDB_API_LISTEN_PORT }}"
            export VASEDB_API_KEY= "${{ secrets.VASEDB_API_KEY }}"
            export VASEDB_CLIENT_URL= "${{ secrets.VASEDB_CLIENT_URL }}"
            export VASEDB_API_PER_IP_CAP= "${{ secrets.VASEDB_API_PER_IP_CAP }}"
            export VASEDB_API_PER_IP_TIME= "${{ secrets.VASEDB_API_PER_IP_TIME }}"
            export VASEDB_API_PER_IP_TIME_UNIT= "${{ secrets.VASEDB_API_PER_IP_TIME_UNIT }}"
            
            docker-compose pull
            docker-compose up -d
